name: Short SHA
description: Quickly gets the Short SHA in an Action
author: Hudson
branding:
  icon: git-commit
  color: black
inputs:
  commit-sha:
    description: "Full length, 40 character SHA-1"
    default: "${{ github.sha }}"
    required: true

outputs:
  sha:
    description: The short SHA

runs:
  using: docker
  image: Dockerfile
  env:
    GIT_SHA: ${{ inputs.commit-sha }}
