name: Get Short SHA
description: Quickly get the Short SHA-1 in your workflow.
author: Hudson
branding:
  icon: git-commit
  color: black
inputs:
  commit-sha:
    description: "Full length, 40 character SHA-1"
    default: "${{ github.sha }}"
    required: true
  length:
    description: "The length of the SHA to cut"
    default: "7"
    required: true
outputs:
  sha:
    description: The short SHA
    value: ${{ steps.make-sha.outputs.sha }}

runs:
  using: composite
  steps:
    - id: make-sha
      run: |
        chmod +x ${GITHUB_ACTION_PATH}/script.sh
        ${GITHUB_ACTION_PATH}/script.sh ${{ inputs.commit-sha }} ${{ inputs.length }}
      shell: bash
