name: CI

on:
  push:

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Action Test
        id: test
        uses: ./

      - name: Marketplace Test
        id: marketplace-test
        uses: hudsonm62/short-sha@v1

      - name: Print Output
        run: |
          echo "Local: ${{ steps.test.outputs.sha }}"
          echo "Marketplace: ${{ steps.marketplace-test.outputs.sha }}"
